### PR TITLE
- Change to correct scroll event

### PR DESCRIPTION
**Pull request by ronaldohoch**
https://github.com/artf/grapesjs-plugin-ckeditor/issues/52

### CODE REVIEW

**Comment by collins-lagat** [comment]
Hi @ronaldohoch. could you include the updated `dist` folder in the PR? Like, run 'npm run build`.

**Comment by ronaldohoch** [comment]
@collins-lagat done.
https://github.com/artf/grapesjs-plugin-ckeditor/pull/53/commits/a74101e2c1b4685fdf6c76ae553b2b1b2b387bdd

**Comment by adiux** [comment]
@collins-lagat can this be merged now?

**Comment by artf** [comment]
Should be fixed in the [latest release](https://github.com/GrapesJS/ckeditor/releases/tag/v1.0.1)

**Pull request closed without merging**
